# Generated by Django 3.0.8 on 2020-08-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_userfollowing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user_id', 'following_user_id')},
        ),
    ]
