# Generated by Django 3.0.8 on 2020-07-31 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filter_watchlist_auction', to='auctions.Auction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filter_watchlist_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
